language: python
python:
  - "3.7"
install:
  - pip install --upgrade setuptools
  - pip install -r requirements3.txt

script:
  - py.test --cov=negbio

after_success:
  - coveralls

notifications:
  email:
    on_success: never # default: change
    on_failure: always
